apiVersion: v1
kind: Pod
metadata:
  name: my-nginx2
  namespace: seoyeon
  labels:
    app: my-nginx2
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80

  - name: http-pinger
    image: busybox
    command: ['sh', '-c', 'while true; do wget -qO- http://localhost:80; sleep 5; done']