
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argo-yeonnex0316-com-tls
  namespace: argocd
spec:
  secretName: argo-yeonnex0316-com-tls
  duration: 2160h #90day
  renewBefore: 360h #before 15day
  issuerRef:
    name: my-issuer
    kind: ClusterIssuer
  commonName: argo.yeonnex0316.store
  dnsNames:
  - argo.yeonnex0316.store